package com.example.hrms.mapper;

import com.example.hrms.dto.EmployeeRequestDTO;
import com.example.hrms.dto.EmployeeResponseDTO;
import com.example.hrms.entity.Employee;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

/**
 * EmployeeMapper
 *
 * MapStruct mapper used to convert:
 *
 * 1. EmployeeRequestDTO  →  Employee Entity
 * 2. Employee Entity     →  EmployeeResponseDTO
 *
 * Why we use this:
 * - Avoid manual object mapping
 * - Keep controller and service clean
 * - Separate DTO layer from Entity layer
 *
 * componentModel = "spring"
 * → Allows Spring to manage this mapper as a Bean.
 */
@Mapper(componentModel = "spring")
public interface EmployeeMapper {

    /**
     * Converts EmployeeRequestDTO to Employee Entity.
     *
     * id is ignored because it is auto-generated by database.
     * active is ignored because default value is true.
     */
    @Mapping(target = "id", ignore = true)
    @Mapping(target = "active", ignore = true)
    Employee toEntity(EmployeeRequestDTO dto);

    /**
     * Converts Employee Entity to EmployeeResponseDTO.
     */
    EmployeeResponseDTO toResponseDTO(Employee employee);
}